final Map<String, String> countryFlags = {
  "Türkiye": "https://flagcdn.com/w320/tr.png",
  "Almanya": "https://flagcdn.com/w320/de.png",
  "Fransa": "https://flagcdn.com/w320/fr.png",
  "İtalya": "https://flagcdn.com/w320/it.png",
  "İspanya": "https://flagcdn.com/w320/es.png",
  "İngiltere": "https://flagcdn.com/w320/gb.png",
  "Japonya": "https://flagcdn.com/w320/jp.png",
  "Brezilya": "https://flagcdn.com/w320/br.png",
  "Arjantin": "https://flagcdn.com/w320/ar.png",
  "Meksika": "https://flagcdn.com/w320/mx.png",
  "Hindistan": "https://flagcdn.com/w320/in.png",
  "Endonezya": "https://flagcdn.com/w320/id.png",
  "Filipinler": "https://flagcdn.com/w320/ph.png",
  "Güney Kore": "https://flagcdn.com/w320/kr.png",
  "Şili": "https://flagcdn.com/w320/cl.png",
  "Kolombiya": "https://flagcdn.com/w320/co.png",
  "Pakistan": "https://flagcdn.com/w320/pk.png",
  "Tayland": "https://flagcdn.com/w320/th.png",
  "Vietnam": "https://flagcdn.com/w320/vn.png",
  "Mısır": "https://flagcdn.com/w320/eg.png",
  "Tunus": "https://flagcdn.com/w320/tn.png",
  "Yunanistan": "https://flagcdn.com/w320/gr.png",
  "Portekiz": "https://flagcdn.com/w320/pt.png",
  "Belçika": "https://flagcdn.com/w320/be.png",
  "İsveç": "https://flagcdn.com/w320/se.png",
  "Danimarka": "https://flagcdn.com/w320/dk.png",
  "Norveç": "https://flagcdn.com/w320/no.png",
  "İsviçre": "https://flagcdn.com/w320/ch.png",
  "Gana": "https://flagcdn.com/w320/gh.png",
  "Kenya": "https://flagcdn.com/w320/ke.png",
  "Kosta Rika": "https://flagcdn.com/w320/cr.png",
  "Moğolistan": "https://flagcdn.com/w320/mn.png",
  "Lübnan": "https://flagcdn.com/w320/lb.png",
  "Kazakistan": "https://flagcdn.com/w320/kz.png",
  "Gürcistan": "https://flagcdn.com/w320/ge.png",
  "Nepal": "https://flagcdn.com/w320/np.png",
  "Avustralya": "https://flagcdn.com/w320/au.png",
  "Kanada": "https://flagcdn.com/w320/ca.png",
  "ABD": "https://flagcdn.com/w320/us.png",
  "Çin": "https://flagcdn.com/w320/cn.png",
  "Rusya": "https://flagcdn.com/w320/ru.png",
  "Suudi Arabistan": "https://flagcdn.com/w320/sa.png",
  "Güney Afrika": "https://flagcdn.com/w320/za.png",
  "Fiji": "https://flagcdn.com/w320/fj.png",
  "Bhutan": "https://flagcdn.com/w320/bt.png",
  "Eritre": "https://flagcdn.com/w320/er.png",
  "Belize": "https://flagcdn.com/w320/bz.png",
  "Vanuatu": "https://flagcdn.com/w320/vu.png",
  "Tonga": "https://flagcdn.com/w320/to.png",
  "Kiribati": "https://flagcdn.com/w320/ki.png",
  "Eswatini": "https://flagcdn.com/w320/sz.png",
  "Surinam": "https://flagcdn.com/w320/sr.png",
  "Guyana": "https://flagcdn.com/w320/gy.png",
  "Dominika": "https://flagcdn.com/w320/dm.png",
  "Barbados": "https://flagcdn.com/w320/bb.png",
  "Grenada": "https://flagcdn.com/w320/gd.png",
  "Bahamalar": "https://flagcdn.com/w320/bs.png",
  "Jamaika": "https://flagcdn.com/w320/jm.png",
  "Trinidad ve Tobago": "https://flagcdn.com/w320/tt.png",
  "Haiti": "https://flagcdn.com/w320/ht.png",
  "Dominik Cumhuriyeti": "https://flagcdn.com/w320/do.png",
  "Küba": "https://flagcdn.com/w320/cu.png",
  "Honduras": "https://flagcdn.com/w320/hn.png",
  "El Salvador": "https://flagcdn.com/w320/sv.png",
  "Guatemala": "https://flagcdn.com/w320/gt.png",
  "Nicaragua": "https://flagcdn.com/w320/ni.png",
  "Panama": "https://flagcdn.com/w320/pa.png",
  "Senegal": "https://flagcdn.com/w320/sn.png",
  "Bolivya": "https://flagcdn.com/w320/bo.png",
  "Peru": "https://flagcdn.com/w320/pe.png",
  "Ekvador": "https://flagcdn.com/w320/ec.png",
  "Katar": "https://flagcdn.com/w320/qa.png",
  "Yeni Zelanda": "https://flagcdn.com/w320/nz.png",
  "İran": "https://flagcdn.com/w320/ir.png",
  "Bangladeş": "https://flagcdn.com/w320/bd.png",
  "Malezya": "https://flagcdn.com/w320/my.png",
  "Myanmar": "https://flagcdn.com/w320/mm.png",
  "Singapur": "https://flagcdn.com/w320/sg.png",
  "Kamboçya": "https://flagcdn.com/w320/kh.png",
  "Lao": "https://flagcdn.com/w320/la.png",
  "Sudan": "https://flagcdn.com/w320/sd.png",
  "Zambiya": "https://flagcdn.com/w320/zm.png",
  "Zimbabve": "https://flagcdn.com/w320/zw.png",
  "Madagaskar": "https://flagcdn.com/w320/mg.png",
  "Botsvana": "https://flagcdn.com/w320/bw.png",
  "Malavi": "https://flagcdn.com/w320/mw.png",
  "Mozambik": "https://flagcdn.com/w320/mz.png",
  "Birleşik Arap Emirlikleri": "https://flagcdn.com/w320/ae.png",
  "Sri Lanka": "https://flagcdn.com/w320/lk.png",
  "Afganistan": "https://flagcdn.com/w320/af.png",
  "Irak": "https://flagcdn.com/w320/iq.png",
  "Suriye": "https://flagcdn.com/w320/sy.png",
  "Özbekistan": "https://flagcdn.com/w320/uz.png",
  "Türkmenistan": "https://flagcdn.com/w320/tm.png",
  "Paraguay": "https://flagcdn.com/w320/py.png",
  "Uruguay": "https://flagcdn.com/w320/uy.png",
  "Venezuela": "https://flagcdn.com/w320/ve.png",
  "Polonya": "https://flagcdn.com/w320/pl.png",
  "Ukrayna": "https://flagcdn.com/w320/ua.png",
  "Finlandiya": "https://flagcdn.com/w320/fi.png",
  "İrlanda": "https://flagcdn.com/w320/ie.png",
  "Hollanda": "https://flagcdn.com/w320/nl.png",
  "Avusturya": "https://flagcdn.com/w320/at.png",
  "Macaristan": "https://flagcdn.com/w320/hu.png",
  "Çekya": "https://flagcdn.com/w320/cz.png",
  "Slovakya": "https://flagcdn.com/w320/sk.png",
  "Bulgaristan": "https://flagcdn.com/w320/bg.png",
  "Romanya": "https://flagcdn.com/w320/ro.png",
  "Hırvatistan": "https://flagcdn.com/w320/hr.png",
  "Sırbistan": "https://flagcdn.com/w320/rs.png",
  "Bosna Hersek": "https://flagcdn.com/w320/ba.png",
  "Kuzey Makedonya": "https://flagcdn.com/w320/mk.png",
  "Arnavutluk": "https://flagcdn.com/w320/al.png",
  "Litvanya": "https://flagcdn.com/w320/lt.png",
  "Letonya": "https://flagcdn.com/w320/lv.png",
  "Estonya": "https://flagcdn.com/w320/ee.png",
  "Moldova": "https://flagcdn.com/w320/md.png",
  "Beyaz Rusya": "https://flagcdn.com/w320/by.png",
  "Azerbeycan": "https://flagcdn.com/w320/az.png",
  "Ermenistan": "https://flagcdn.com/w320/am.png",
  "Slovenya": "https://flagcdn.com/w320/si.png",
  "Lüksemburg": "https://flagcdn.com/w320/lu.png",
  "Malta": "https://flagcdn.com/w320/mt.png",
  "Kıbrıs": "https://flagcdn.com/w320/cy.png",
  "İzlanda": "https://flagcdn.com/w320/is.png",
  "Morityus": "https://flagcdn.com/w320/mu.png",
  "Komor": "https://flagcdn.com/w320/km.png",
  "Seyşeller": "https://flagcdn.com/w320/sc.png",
  "Karadağ": "https://flagcdn.com/w320/me.png",
  "Fas": "https://flagcdn.com/w320/ma.png",
  "Cezayir": "https://flagcdn.com/w320/dz.png",
  "Libya": "https://flagcdn.com/w320/ly.png",
  "Nijerya": "https://flagcdn.com/w320/ng.png",
  "Etiyopya": "https://flagcdn.com/w320/et.png",
  "Somali": "https://flagcdn.com/w320/so.png",
  "Uganda": "https://flagcdn.com/w320/ug.png",
  "Tanzanya": "https://flagcdn.com/w320/tz.png",
  "Ruanda": "https://flagcdn.com/w320/rw.png",
  "Burundi": "https://flagcdn.com/w320/bi.png",
  "Kongo": "https://flagcdn.com/w320/cg.png",
  "Demokratik Kongo Cumhuriyeti": "https://flagcdn.com/w320/cd.png",
  "Angola": "https://flagcdn.com/w320/ao.png",
  "Namibya": "https://flagcdn.com/w320/na.png",
  "Mali": "https://flagcdn.com/w320/ml.png",
  "Nijer": "https://flagcdn.com/w320/ne.png",
  "Çad": "https://flagcdn.com/w320/td.png",
  "Orta Afrika Cumhuriyeti": "https://flagcdn.com/w320/cf.png",
  "Kamerun": "https://flagcdn.com/w320/cm.png",
  "Gabon": "https://flagcdn.com/w320/ga.png",
  "Ekvator Ginesi": "https://flagcdn.com/w320/gq.png",
  "Gine": "https://flagcdn.com/w320/gn.png",
  "Gine-Bissau": "https://flagcdn.com/w320/gw.png",
  "Liberya": "https://flagcdn.com/w320/lr.png",
  "Fildişi Sahili": "https://flagcdn.com/w320/ci.png",
  "Burkina Faso": "https://flagcdn.com/w320/bf.png",
  "Togo": "https://flagcdn.com/w320/tg.png",
  "Benin": "https://flagcdn.com/w320/bj.png",
  "Sierra Leone": "https://flagcdn.com/w320/sl.png",
  "Gambiya": "https://flagcdn.com/w320/gm.png",
  "Mauritanya": "https://flagcdn.com/w320/mr.png",
  "Kuzey Kore": "https://flagcdn.com/w320/kp.png",
  "Papa Yeni Gine": "https://flagcdn.com/w320/pg.png",
  "Solomon Adaları": "https://flagcdn.com/w320/sb.png",
  "Samoa": "https://flagcdn.com/w320/ws.png",
  "Mikronezya": "https://flagcdn.com/w320/fm.png",
  "Marshall Adaları": "https://flagcdn.com/w320/mh.png",
  "Palau": "https://flagcdn.com/w320/pw.png",
  "Nauru": "https://flagcdn.com/w320/nr.png",
  "Umman": "https://flagcdn.com/w320/om.png",
  "Bahreyn": "https://flagcdn.com/w320/bh.png",
  "Kuveyt": "https://flagcdn.com/w320/kw.png",
  "Ürdün": "https://flagcdn.com/w320/jo.png",
  "Yemen": "https://flagcdn.com/w320/ye.png",
  "Kırgızistan": "https://flagcdn.com/w320/kg.png",
  "Tacikistan": "https://flagcdn.com/w320/tj.png",
  "Antigua ve Barbuda": "https://flagcdn.com/w320/ag.png",
  "Saint Kitts ve Nevis": "https://flagcdn.com/w320/kn.png",
  "Saint Lucia": "https://flagcdn.com/w320/lc.png",
  "Saint Vincent ve Grenadinler": "https://flagcdn.com/w320/vc.png",
  "Cabo Verde": "https://flagcdn.com/w320/cv.png",
  "Sao Tome ve Principe": "https://flagcdn.com/w320/st.png",
  "Maldivler": "https://flagcdn.com/w320/mv.png",
  "Timor-Leste": "https://flagcdn.com/w320/tl.png",
  "Vatikan": "https://flagcdn.com/w320/va.png",
  "Lihtenştayn": "https://flagcdn.com/w320/li.png",
  "Andorra": "https://flagcdn.com/w320/ad.png",
  "Monako": "https://flagcdn.com/w320/mc.png",
  "San Marino": "https://flagcdn.com/w320/sm.png",
  "Brunei": "https://flagcdn.com/w320/bn.png",
  "Tuvalu": "https://flagcdn.com/w320/tv.png",
  "Lesotho": "https://flagcdn.com/w320/ls.png",
  "Djibouti": "https://flagcdn.com/w320/dj.png",
};
